export const rentals = [
  {
    id: 1,
    name: "Rainbow Orca Base",
    type: "Walking (Sit-on-Top)",
    length: "420 cm",
    width: "83 cm",
    capacity: "230 kg",
    seats: "2 adults + 1 child",
    priceHour: "€10 per hour",
    priceDay: "€45 per day",
    image: "/images/rental/kayak_orca-base.png",
  },
  {
    id: 2,
    name: "Kayak Ocean Duo",
    type: "Walking (Sit-on-Top)",
    length: "370 cm",
    width: "88 cm",
    capacity: "220 kg",
    seats: "2 adults + 1 child",
    priceHour: "€10 per hour",
    priceDay: "€45 per day",
    image: "/images/rental/kayak_ocean-duo.png",
  },
  {
    id: 3,
    name: "Kayak Ocean Quatro",
    type: "Walking (Sit-on-Top)",
    length: "412 cm",
    width: "90 cm",
    capacity: "260 kg",
    seats: "2 adults + 2 child",
    priceHour: "€10 per hour",
    priceDay: "€45 per day",
    image: "/images/rental/quatro.png",
  },
  {
    id: 4,
    name: "Kayak Optimo",
    type: "Walking (Sit-on-Top)",
    length: "432 cm",
    width: "93 cm",
    capacity: "300 kg",
    seats: "2 adults + 1 child",
    priceHour: "€10 per hour",
    priceDay: "€45 per day",
    image: "/images/rental/Optimo.png",
  },
  {
    id: 5,
    name: "Kayak Rytmo",
    type: "Touring (Sit-on-Top)",
    length: "460 cm",
    width: "72 cm",
    capacity: "180 kg",
    seats: "1 adult",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/Rytmo.png",
  },
  {
    id: 6,
    name: "Kayak Mid-Way",
    type: "Touring (Sit-on-Top)",
    length: "440 cm",
    width: "65 cm",
    capacity: "140 kg",
    seats: "1 adult",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/Mid.png",
  },
  {
    id: 7,
    name: "Kayak Makao",
    type: "Walking (Sit-on-Top)",
    length: "273 cm",
    width: "79 cm",
    capacity: "140 kg",
    seats: "1 adult",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/Makao.png",
  },
  {
    id: 8,
    name: "Kayak Tempo",
    type: "Walking (Sit-on-Top)",
    length: "450 cm",
    width: "67 cm",
    capacity: "740 kg",
    seats: "1 adult",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/Tempo.png",
  },
  {
    id: 9,
    name: "Gladiator Pro 10'6",
    type: "Walking",
    length: "10’6’ (323 cm)",
    width: "86 cm",
    weight: '9.5 kg',
    capacity: "up to 120 kg",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/Gladiator.png",
  },
  {
    id: 10,
    name: "Gladiator Pro 10'8",
    type: "Walking",
    length: "10’8’ (323 cm)",
    width: "86 cm",
    weight: '11 kg',
    capacity: "up to 150 kg",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/10'8.png",
  },
  {
    id: 11,
    name: "Gladiator Pro 12'6",
    type: "Touring",
    length: "12’6’’ (384 cm)",
    width: "81 cm",
    weight: '11 kg',
    capacity: "up to 220 kg",
    priceHour: "€10 per hour",
    priceDay: "€30 per day",
    image: "/images/rental/12'6.png",
  },
];
